// /etc/apt/apt.conf.d/20auto-upgrades
// Aktiviert das tägliche Ausführen von unattended-upgrade.

APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
