#!/bin/bash
# scripts/add-site.sh
#
# Interaktiver Wizard für eine neue Reverse-Proxy-Site.
# Generiert die nginx-Config, committet, pusht — und optional führt
# cert-request + enable-site per SSH auf beiden Nodes aus.
#
# WO LAUFEN: Auf dem Dev-Rechner (Laptop), nicht auf den VMs.
#   Grund: Push-Zugriff aufs Repo läuft vom Laptop, die VMs haben
#   read-only Deploy-Keys. Cert + Enable passieren via SSH auf den
#   Nodes (mit --apply).
#
# Aufrufe:
#   ./scripts/add-site.sh                  # interaktiv, Datei + commit + push
#   ./scripts/add-site.sh --apply          # zusätzlich SSH zu beiden Nodes
#   ./scripts/add-site.sh --no-push        # Datei + commit, kein push
#   ./scripts/add-site.sh --help

set -euo pipefail

# ============================================================================
# Repo-Root finden
# ============================================================================
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || {
    echo "FEHLER: nicht in einem git-Repo. cd ins Reverse-Proxy-Repo zuerst." >&2
    exit 1
}
cd "$REPO_ROOT"

# Sanity: dies ist tatsächlich das Reverse-Proxy-Repo
[[ -d nginx/sites-available ]] || {
    echo "FEHLER: 'nginx/sites-available/' nicht gefunden — falsches Repo?" >&2
    exit 1
}

# ============================================================================
# Argumente
# ============================================================================
APPLY=0
NO_PUSH=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --apply)    APPLY=1; shift ;;
        --no-push)  NO_PUSH=1; shift ;;
        -h|--help)
            sed -n '2,/^$/p' "$0" | sed 's/^# \?//'
            exit 0 ;;
        *) echo "Unbekanntes Argument: $1" >&2; exit 1 ;;
    esac
done

# ============================================================================
# Eingaben
# ============================================================================
echo
echo "=== Neue Reverse-Proxy-Site einrichten ==="
echo

while true; do
    read -rp "Domain (z.B. pihole.example.com): " DOMAIN
    [[ -n "$DOMAIN" ]] || continue
    if [[ "$DOMAIN" =~ ^[a-zA-Z0-9][a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
        break
    fi
    echo "  Ungültiges Format — sollte aussehen wie 'sub.example.com'"
done

DEFAULT_NAME=$(echo "$DOMAIN" | cut -d. -f1)
read -rp "Site-Name (Dateiname ohne .conf) [${DEFAULT_NAME}]: " SITE_NAME
SITE_NAME=${SITE_NAME:-$DEFAULT_NAME}

while true; do
    read -rp "Backend-URL (z.B. http://10.0.0.50:8080): " BACKEND
    if [[ "$BACKEND" =~ ^https?://[a-zA-Z0-9.-]+(:[0-9]+)?(/.*)?$ ]]; then
        break
    fi
    echo "  Ungültiges Format — sollte aussehen wie 'http://10.0.0.50:8080'"
done

read -rp "WebSocket-Support? [y/N]: " ans
WS=0
[[ "$ans" =~ ^[Yy]$ ]] && WS=1

# ============================================================================
# Konflikte
# ============================================================================
SITE_FILE="nginx/sites-available/${SITE_NAME}.conf"
if [[ -f "$SITE_FILE" ]]; then
    echo
    echo "WARNUNG: $SITE_FILE existiert bereits."
    read -rp "Überschreiben? [y/N]: " ans
    [[ "$ans" =~ ^[Yy]$ ]] || { echo "Abgebrochen."; exit 1; }
fi

# ============================================================================
# Plan-Anzeige
# ============================================================================
cat <<EOF

==================== Plan ====================
  Domain          : $DOMAIN
  Site-Name       : $SITE_NAME
  Backend         : $BACKEND
  WebSocket       : $([[ $WS -eq 1 ]] && echo "ja" || echo "nein")
  Datei           : $SITE_FILE
  Commit + Push   : $([[ $NO_PUSH -eq 0 ]] && echo "ja" || echo "nur commit")
  SSH-Apply       : $([[ $APPLY -eq 1 ]] && echo "ja (cert + enable auf beiden Nodes)" || echo "nein (nur Datei + push, dann manuell)")
==============================================

EOF
read -rp "Fortfahren? [Y/n]: " ans
[[ "${ans:-y}" =~ ^[Nn]$ ]] && { echo "Abgebrochen."; exit 0; }

# ============================================================================
# nginx-Config generieren
# ============================================================================
{
    echo "# Auto-generated by add-site.sh am $(date -Iseconds)"
    echo "# Domain: $DOMAIN  →  Backend: $BACKEND"
    echo
    echo "# === HTTP → HTTPS Redirect (mit ACME-Pfad für certbot) ==="
    echo "server {"
    echo "    listen 80;"
    echo "    listen [::]:80;"
    echo "    server_name $DOMAIN;"
    echo "    include /etc/nginx/snippets/acme-challenge.conf;"
    echo "    location / {"
    echo "        return 301 https://\$host\$request_uri;"
    echo "    }"
    echo "}"
    echo
    echo "# === HTTPS ==="
    echo "server {"
    echo "    # 'listen … http2' (alte Form) für Kompatibilität nginx 1.18+"
    echo "    listen 443 ssl http2;"
    echo "    listen [::]:443 ssl http2;"
    echo "    server_name $DOMAIN;"
    echo
    echo "    ssl_certificate     /etc/letsencrypt/live/$DOMAIN/fullchain.pem;"
    echo "    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;"
    echo "    ssl_trusted_certificate /etc/letsencrypt/live/$DOMAIN/chain.pem;"
    echo
    echo "    access_log /var/log/nginx/${SITE_NAME}-access.log main;"
    echo "    error_log  /var/log/nginx/${SITE_NAME}-error.log warn;"
    echo
    echo "    limit_conn conn_per_ip 50;"
    echo
    echo "    location / {"
    echo "        limit_req zone=general burst=50 nodelay;"
    echo "        proxy_pass $BACKEND;"
    echo "        include /etc/nginx/snippets/proxy-defaults.conf;"
    if [[ $WS -eq 1 ]]; then
        echo "        include /etc/nginx/snippets/websocket.conf;"
    fi
    echo "    }"
    echo "}"
} > "$SITE_FILE"

echo
echo "✓ Erstellt: $SITE_FILE"

# ============================================================================
# Git
# ============================================================================
git add "$SITE_FILE"
git commit -m "site: $DOMAIN → $BACKEND"
echo "✓ Committed"

if [[ $NO_PUSH -eq 0 ]]; then
    git push
    echo "✓ Gepusht"
else
    echo "→ --no-push: nicht gepusht. Manuell: 'git push'"
fi

# ============================================================================
# SSH-Apply (optional)
# ============================================================================
if [[ $APPLY -eq 1 ]]; then
    echo
    echo "=== Auf den Nodes ausführen ==="
    read -rp "SSH-Target für proxy01 (MASTER) [root@proxy01]: " SSH_M
    SSH_M=${SSH_M:-root@proxy01}
    read -rp "SSH-Target für proxy02 (BACKUP) [root@proxy02]: " SSH_B
    SSH_B=${SSH_B:-root@proxy02}

    echo
    echo "→ Warte 30 s, damit der Repo-Pull-Timer auf den Nodes greift..."
    echo "  (Alternativ in der Status-Site: Ops → 'Repo pullen + deployen')"
    sleep 30

    echo
    echo "→ proxy01 (MASTER): cert-request + enable-site"
    if ! ssh "$SSH_M" "cd /opt/reverse-proxy && git pull --ff-only && ./scripts/cert-request.sh '$DOMAIN' && ./scripts/enable-site.sh '$SITE_NAME'"; then
        echo
        echo "FEHLER auf proxy01. Manuell:"
        echo "  ssh $SSH_M"
        echo "  cd /opt/reverse-proxy && git pull --ff-only"
        echo "  ./scripts/cert-request.sh $DOMAIN"
        echo "  ./scripts/enable-site.sh $SITE_NAME"
        exit 1
    fi

    echo
    echo "→ proxy02 (BACKUP): enable-site"
    if ! ssh "$SSH_B" "cd /opt/reverse-proxy && git pull --ff-only && ./scripts/enable-site.sh '$SITE_NAME'"; then
        echo
        echo "FEHLER auf proxy02. Manuell:"
        echo "  ssh $SSH_B"
        echo "  cd /opt/reverse-proxy && git pull --ff-only"
        echo "  ./scripts/enable-site.sh $SITE_NAME"
        exit 1
    fi

    echo
    echo "================================================================"
    echo " ✓ $DOMAIN ist live"
    echo "================================================================"
    echo "Test: curl -I https://$DOMAIN"
else
    cat <<EOF

=== Nächste Schritte (manuell auf den Nodes) ===

Auf proxy01 (MASTER):
  ssh root@proxy01
  cd /opt/reverse-proxy && git pull --ff-only
  ./scripts/cert-request.sh $DOMAIN
  ./scripts/enable-site.sh $SITE_NAME

Auf proxy02 (BACKUP):
  ssh root@proxy02
  cd /opt/reverse-proxy && git pull --ff-only
  ./scripts/enable-site.sh $SITE_NAME

Tipp: nächstes Mal '--apply' nutzen — das erledigt das automatisch
über Tailscale-SSH (root@proxy01 / root@proxy02 dank MagicDNS).

EOF
fi
