# /etc/nginx/snippets/acme-challenge.conf
# In jedem Port-80-Server einbinden, der ein Let's-Encrypt-Zertifikat haben soll

location /.well-known/acme-challenge/ {
    root /var/www/letsencrypt;
    default_type "text/plain";
    allow all;
}
